In [62]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [63]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [64]:
# 读取数据集
def load_array(data_arrays, batch_size, is_train=True):
    """构造一个pytorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [65]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [66]:
# iter() 函数用来生成迭代器。
# next() 返回迭代器的下一个项目。
next(iter(data_iter))

[tensor([[-0.1663, -0.7315],
         [ 0.6240,  0.6349],
         [-0.6747, -0.6682],
         [ 0.4898, -0.0737],
         [-0.2786,  0.3154],
         [ 1.0220,  0.6993],
         [ 1.1415,  0.2745],
         [-0.5738,  1.0194],
         [ 1.6769,  1.4827],
         [ 0.0822, -0.4000]]),
 tensor([[ 6.3624],
         [ 3.3088],
         [ 5.1091],
         [ 5.4268],
         [ 2.5748],
         [ 3.8773],
         [ 5.5521],
         [-0.4296],
         [ 2.5133],
         [ 5.7303]])]

In [67]:
# 定义模型
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [68]:
# 初始化模型参数
"""
a = net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)
a
tensor([[-0.0036, -0.0091]])
"""
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [69]:
# 定义损失函数
loss = nn.MSELoss()

In [70]:
# 定义优化算法
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [71]:
# 训练
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        # 初始化梯度为0
        trainer.zero_grad()
        l.backward()
        # 在一个batch_size中更新一次参数空间用step()方法
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch+1}, loss {l:f}')

epoch 1, loss 0.000240
epoch 2, loss 0.000097
epoch 3, loss 0.000097


In [72]:
w = net[0].weight.data
print('w的估计误差: ', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差: ', true_b - b)

w的估计误差:  tensor([-0.0005, -0.0006])
b的估计误差:  tensor([-0.0004])
